### PR TITLE
Add database tables required for consent management

### LINKED ISSUE #198: Table 'WSO2IS_IDENTITY_DB.CM_PURPOSE' doesn't exist
**Description:**
Hi, I get this error in the docker image wso2/wso2is:5.10.0 when I try to activated and tested the selft register proceed.

```identity-server_1  | [2020-04-07 02:50:12,673] [125d4bd4-ad4f-4b99-925f-c18181e66686] ERROR {org.wso2.carbon.consent.mgt.endpoint.impl.ConsentsApiServiceImpl} - Error occurred while listing purpose from DB for group: SELF-SIGNUP, groupType: SYSTEM limit: 100 and offset: 0. org.wso2.carbon.consent.mgt.core.exception.ConsentManagementServerException: Error occurred while listing purpose from DB for group: SELF-SIGNUP, groupType: SYSTEM limit: 100 and offset: 0.
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.dao.impl.PurposeDAOImpl.listPurposes(PurposeDAOImpl.java:249)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.listPurposes(ConsentManagerImpl.java:262)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.PrivilegedConsentManagerImpl$5.execute(PrivilegedConsentManagerImpl.java:226)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.PrivilegedConsentManagerImpl$5.execute(PrivilegedConsentManagerImpl.java:222)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.model.ConsentInterceptorTemplate.executeWith(ConsentInterceptorTemplate.java:56)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.PrivilegedConsentManagerImpl.listPurposes(PrivilegedConsentManagerImpl.java:222)
identity-server_1  |    at org.wso2.carbon.consent.mgt.endpoint.impl.ConsentsApiServiceImpl.getPurposeListResponseDTO(ConsentsApiServiceImpl.java:420)
.
.
.
identity-server_1  | Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s'SELECT ID, NAME, DESCRIPTION, PURPOSE_GROUP, GROUP_TYPE, TENANT_ID FROM CM_PURPOSE WHERE TENANT_ID = ? AND PURPOSE_GROUP LIKE ? AND GROUP_TYPE LIKE ? ORDER BY ID ASC LIMIT ? OFFSET ?
identity-server_1  |    at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.executeQuery(JdbcTemplate.java:169)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.dao.impl.PurposeDAOImpl.listPurposes(PurposeDAOImpl.java:233)
identity-server_1  |    ... 61 more
identity-server_1  | Caused by: java.sql.SQLSyntaxErrorException: Table 'WSO2IS_IDENTITY_DB.CM_PURPOSE' doesn't exist
identity-server_1  |    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
identity-server_1  |    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
```
**Suggested Labels:**
wso2is:5.10.0

**Affected Product Version:**
docker image wso2/wso2is:5.10.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. git clone $url_repo:tag-5.10.0
1. docker-compose up -d
1. Activate the self-register in the admin-console
1. Go to portal page https://localhost:9443/user-portal and clic in Create Account
1. Write a new username and clic into *Proceed to Self Register*

**Related Issues:**
https://github.com/wso2/product-is/issues/3564

### PR DESCRIPTION
**Pull request by ThilinaManamgoda**

### CODE REVIEW

**Comment by omindu** [comment]
@ThilinaManamgoda can we add the same changes to the master branch as well ?

**Comment by chirangaalwis** [comment]
@omindu yes we'll be merging this change to `master` branch as well, since this is the latest IAM version.

**Comment by omindu** [comment]
Thanks folks for getting this fixed!

**Comment by omindu** [comment]
@chirangaalwis @ThilinaManamgoda can we close https://github.com/wso2/docker-is/issues/198 if these are added to master branch ?

**Comment by chirangaalwis** [comment]
Closed the issue. @ThilinaManamgoda let us perform a release with this fix and then push the content to `master` branch.

**Comment by jpvadell** [comment]
The same problem appears in docker-is 6.0.0. I added the tables by hand and works.

**Comment by vatrox-it** [comment]
The same problem appears in docker-is 6.1.0. I added the tables by hand and works.

**Pull request merged**
